### ISSUE TITLE
index out of range crash

### ISSUE THREAD

**Issue by b3dk7** [kgretzky/evilginx2#1096]
server crashed. happened while there was an active lure. here trace

```
panic: runtime error: index out of range [1] with length 1

goroutine 35318 [running]:
github.com/inconshreveable/go-vhost.readClientHello({0xd3c700?, 0xc0006177a0?})
        /home/snoop/github/evilgophish/evilginx3/vendor/github.com/inconshreveable/go-vhost/tls.go:259 +0x2b3
github.com/inconshreveable/go-vhost.TLS({0xd440b8, 0xc000498108})
        /home/snoop/github/evilgophish/evilginx3/vendor/github.com/inconshreveable/go-vhost/tls.go:91 +0x19b
github.com/kgretzky/evilginx2/core.(*HttpProxy).httpsWorker.func1({0xd440b8, 0xc000498108})
        /home/snoop/github/evilgophish/evilginx3/core/http_proxy.go:1745 +0xd0
created by github.com/kgretzky/evilginx2/core.(*HttpProxy).httpsWorker in goroutine 24
        /home/snoop/github/evilgophish/evilginx3/core/http_proxy.go:1740 +0x192

```

**Comment by jackbaron** [comment]
@b3dk7, have you found a solution for this?

**Comment by Hosted-EU** [comment]
👍✅ https://youtu.be/Ifuj1S9kTFI?si=PcAmtWjjmZM3zaSN

**Comment by Hosted-EU** [comment]
Join new Evilginx Group Chat 🔥https://t.me/evilginx_group
