### ISSUE TITLE
evilginx 3.3 crash

### ISSUE THREAD

**Issue by a725970** [kgretzky/evilginx2#1117]
: panic: runtime error: invalid memory address or nil pointer dereference                                                                                                                                 
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x8e6c5a]                              

goroutine 14013 [running]:                        
github.com/kgretzky/evilginx2/core.NewHttpProxy.func3(0xc00047e510, 0x40edc8?)                                                                                                                            
        /root/evilginx2/core/http_proxy.go:933 +0x69a                                                
github.com/elazarl/goproxy.FuncRespHandler.Handle(0x10?, 0x969840?, 0xc0004003f0?)                                                                                                                        
        /root/evilginx2/vendor/github.com/elazarl/goproxy/actions.go:35 +0x22                                                                                                                             
github.com/elazarl/goproxy.(*ProxyConds).Do.func1(0x969840?, 0xc0005c09c0)                                                                                                                                
        /root/evilginx2/vendor/github.com/elazarl/goproxy/dispatcher.go:300 +0x13a                                                                                                                        
github.com/elazarl/goproxy.FuncRespHandler.Handle(0xc000290e29?, 0xa34db6?, 0x0?)                                                                                                                         
        /root/evilginx2/vendor/github.com/elazarl/goproxy/actions.go:35 +0x22                                                                                                                             
github.com/elazarl/goproxy.(*ProxyHttpServer).filterResponse(...)                                    
        /root/evilginx2/vendor/github.com/elazarl/goproxy/proxy.go:75                                
github.com/elazarl/goproxy.(*ProxyHttpServer).handleHttps.func2()                                    
        /root/evilginx2/vendor/github.com/elazarl/goproxy/https.go:255 +0xf3e                                                                                                                             
created by github.com/elazarl/goproxy.(*ProxyHttpServer).handleHttps                                 
        /root/evilginx2/vendor/github.com/elazarl/goproxy/https.go:206 +0x611                                                                                                                             
exit status 2

happened many times

**Comment by Dazmed707** [comment]
send me messagge for help install @stevesec

**Comment by Hosted-EU** [comment]
Join new Evilginx Group Chat 🔥https://t.me/evilginx_group
